-- ----------------------------------------------------------------------------------
-- -- Dashboard
-- ----------------------------------------------------------------------------------
return {}
-- return {
--     {
--         "glepnir/dashboard-nvim",
--         config = function()
--             abbrev("dash", "Dashboard")
--             local db = require("dashboard")
--             db.custom_center = {
--                 {
--                     icon = "  ",
--                     desc = "Recently opened files                   ",
--                     action = "Telescope oldfiles",
--                     shortcut = "SPC f r"
--                 },
--                 {
--                     icon = "  ",
--                     desc = "Find File                               ",
--                     action = "Telescope find_files",
--                     shortcut = "SPC f f"
--                 },
--                 {
--                     icon = "  ",
--                     desc = "File Browser                            ",
--                     action = "Telescope file_browser",
--                     shortcut = "SPC f n"
--                 },
--                 {
--                     icon = "  ",
--                     desc = "Vim Wiki                                ",
--                     action = "VimwikiIndex",
--                     shortcut = "SPC f w"
--                 },
--             }
--             db.custom_header = {
--                 '                                    @       @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@    ',
--                 '                                 @@@@       @@@@@@@@@@@@@@@@@@@@@@@@@@@@@       ',
--                 '                               @@@@@@       @@@@@@@@@@@@@@@@@@@@@@@@@@@         ',
--                 '                            @@@@@@@@@       @@@@@@@@@@@@@@@@@@@@@@@@            ',
--                 '                          @@@@@@@@@@@       @@@@@@@@@@@@@@@@@@@@@@              ',
--                 '                       @@@@@@@@@@@@@@       @@@@@@@@@@@@@@@@@@@                 ',
--                 '                     @@@@@@@@@@@@@@@@       @@@@@@@@@@@@@@@@@                   ',
--                 '                  @@@@@@@@@@@@@@@@@@@       @@@@@@@@@@@@@@                      ',
--                 '                @@@@@@@@@@@@@@@@@@@@@       @@@@@@@@@@@@                        ',
--                 '             @@@@@@@@@@@@@@@@@@@@@@@@       @@@@@@@@@                           ',
--                 '           @@@@@@@@@@@@@@@@@@@@@@@@@@       @@@@@@@                             ',
--                 '        @@@@@@@@@@@@@@@@@@@@@@@@@@@@@       @@@@                                ',
--                 '      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@       @@                                  ',
--             }
--             db.custom_footer = { '', '💿 Listen kid, dont trust anyone who don\'t like Avicii' }
--         end
--     }
-- }
